
#Makefile
CXX = g++
SRCFILES = runDBMS.cpp DBMS.cpp Database.cpp Relation.cpp Tuple.cpp
CXXFLAGS = -std=c++11 -Wall -g -O0 -o P3

all:
	$(CXX) $(SRCFILES) $(CXXFLAGS)


#USE:		./P3 true PA3_test.sql dbmsSave.txt dbmsMetrics.txt